server:
  port: 8080
  servlet:
    context-path: /api-crbc

spring:
  application:
    name: Criminal Record Bureau Check
  profiles:
    active: @spring.profiles.active@
  jpa:
    properties:
      hibernate:
        types:
          print:
            banner: false
  output:
    ansi:
      enabled: ALWAYS

